global:
  scrape_interval: 10s
  evaluation_interval: 1m
  external_labels:
    monitor: 'my-app-monitor'
scrape_configs:
  - job_name: 'monitoring-app'
    metrics_path: '/actuator/prometheus'
    static_configs:
      - targets: ['host.docker.internal:8080']