# docker compose --env-file .env -f docker-compose.dev.yaml up -d

# docker compose --env-file .env -f docker-compose.dev.yaml down -v

services:
  mysql:
    image: mysql:latest
    container_name: LitHub_mysql_dev
    ports:
      - "3309:3306"
    environment:
      MYSQL_ROOT_PASSWORD: 1234
      MYSQL_DATABASE: LitHub-dev
    tmpfs:
      - /var/lib/mysql
    networks:
      - dev_network

  rabbitmq:
    image: rabbitmq:3-management
    container_name: rabbitmq_dev
    ports:
      - "5672:5672"
      - "15672:15672"
    environment:
      - RABBITMQ_DEFAULT_USER=guest
      - RABBITMQ_DEFAULT_PASS=guest
    networks:
      - dev_network

  redis:
    image: redis:latest
    container_name: LitHub_redis_dev
    ports:
      - "6380:6379"
    tmpfs:
      - /data
    command: redis-server --appendonly no
    networks:
      - dev_network

  prometheus:
    image: prom/prometheus
    container_name: prometheus_dev
    ports:
      - "9090:9090"
    volumes:
      - ./prometheus:/etc/prometheus
    command:
      - "--config.file=/etc/prometheus/prometheus.yml"
    networks:
      - dev_network

  grafana:
    image: grafana/grafana
    container_name: grafana_dev
    ports:
      - "3000:3000"
    environment:
      - GF_SECURITY_ADMIN_PASSWORD=admin
    depends_on:
      - prometheus
    networks:
      - dev_network

networks:
  dev_network:
    driver: bridge