# docker-compose --env-file /c/Users/Sojinyoung/Desktop/LitHub/backend/.env -f /c/Users/Sojinyoung/Desktop/LitHub/backend/docker/dev/docker-compose.dev.yaml up -d

services:
  mysql:
    image: mysql:8.0
    container_name: ${MYSQL_CONTAINER_NAME_DEV}
    ports:
      - "${MYSQL_PORT_DEV}:3306"
    environment:
      MYSQL_ROOT_PASSWORD: ${MYSQL_PASSWORD_DEV}
      MYSQL_DATABASE: ${MYSQL_DATABASE_DEV}
      MYSQL_USER: ${MYSQL_USERNAME_DEV}
      MYSQL_PASSWORD: ${MYSQL_PASSWORD_DEV}
    volumes:
      - ${VOLUME_MYSQL}:/var/lib/mysql
    networks:
      - ${NETWORK_NAME_DEV}

  redis:
    image: redis:latest
    container_name: ${REDIS_CONTAINER_NAME_DEV}
    ports:
      - "${REDIS_PORT_MAPPING_DEV}"
    volumes:
      - ${VOLUME_REDIS}:/data
    command: redis-server --appendonly yes
    networks:
      - ${NETWORK_NAME_DEV}

  influxdb:
    image: influxdb:1.8
    container_name: influxdb_dev
    ports:
      - "8086:8086"
    environment:
      - INFLUXDB_DB=k6
    volumes:
      - influxdb_data:/var/lib/influxdb
    networks:
      - ${NETWORK_NAME_DEV}

  grafana:
    image: grafana/grafana
    container_name: grafana_dev
    ports:
      - "3000:3000"
    environment:
      - GF_SECURITY_ADMIN_PASSWORD=admin
    depends_on:
      - influxdb
    networks:
      - ${NETWORK_NAME_DEV}

  k6:
    image: grafana/k6
    container_name: k6_dev
    volumes:
      - ../../k6:/scripts
    working_dir: /scripts
    command: [
      "run",
      "--out",
      "influxdb=http://influxdb_dev:8086/k6",
      "login-and-test.js"
    ]
    depends_on:
      - mysql
      - redis
      - influxdb
    networks:
      - ${NETWORK_NAME_DEV}

volumes:
  mysql_data:
  redis_data:
  influxdb_data:

networks:
  dev_network:
    driver: bridge
