# application.yml

spring:
  profiles:
    active: dev

  servlet:
    multipart:
      max-file-size: 5MB
      max-request-size: 20MB

  jwt:
    secret: ${JWT_SECRET}

  mail:
    host: ${MAIL_HOST}
    port: ${MAIL_PORT}
    username: ${MAIL_USERNAME}
    password: ${MAIL_PASSWORD}
    properties:
      mail.smtp.auth: true
      mail.smtp.ssl.enable: true
      mail.smtp.ssl.trust: ${MAIL_HOST}

server:
  port: 8080
  tomcat:
    max-swallow-size: 1GB
    max-http-form-post-size: 1GB

springdoc:
  api-docs:
    enabled: true
  default-produces-media-type: application/json;charset=UTF-8

management:
  server:
    port: 8080
  endpoints:
    web:
      exposure:
        include: health, metrics, prometheus # env 는 disable
  health:
    redis:
      enabled: false

slack:
  webhook:
    url: ${SLACK_WEB_HOOK_URL}

custom:
  upload:
    max-image-size: 5MB
    max-file-size: 20MB

logging:
  level:
    org.hibernate.SQL: INFO
    org.hibernate.orm.jdbc.bind: OFF
    org.hibernate.orm.jdbc.extract: OFF
    org.springframework.transaction.interceptor: OFF