# application.yml

spring:
  profiles:
    active: dev
    include: secret

  servlet:
    multipart:
      max-file-size: 5MB
      max-request-size: 20MB

  jwt:
    secret: ${custom.jwt.secret}

  mail:
    host: ${custom.mail.host}
    port: ${custom.mail.port}
    username: ${custom.mail.username}
    password: ${custom.mail.password}
    properties:
      mail.smtp.auth: true
      mail.smtp.ssl.enable: true
      mail.smtp.ssl.trust: ${custom.mail.host}

server:
  port: 8080
  tomcat:
    max-swallow-size: 1GB
    max-http-form-post-size: 1GB

springdoc:
  api-docs:
    enabled: true
  default-produces-media-type: application/json;charset=UTF-8

slack:
  webhook:
    url: ${custom.slack.webhook-url}

custom:
  upload:
    max-image-size: 5MB
    max-file-size: 20MB

logging:
  level:
    org.hibernate.SQL: INFO
    org.hibernate.orm.jdbc.bind: OFF
    org.hibernate.orm.jdbc.extract: OFF
    org.springframework.transaction.interceptor: OFF