# application-prod.yml

server:
  forward-headers-strategy: native

spring:
  datasource:
    url: ${custom.prod.db.url}
    username: ${custom.prod.db.username}
    password: ${custom.prod.db.password}
    driver-class-name: com.mysql.cj.jdbc.Driver

  data:
    redis:
      sentinel:
        master: ${custom.prod.redis.sentinel.master}
        nodes:  ${custom.prod.redis.sentinel.nodes}
      password: ${custom.prod.redis.password}

  rabbitmq:
    host: ${custom.prod.rabbitmq.host}
    port: ${custom.prod.rabbitmq.port}
    username: ${custom.prod.rabbitmq.username}
    password: ${custom.prod.rabbitmq.password}
    listener:
      simple:
        retry:
          enabled: true
          initial-interval: 1000
          max-attempts: 5
          max-interval: 10000
          multiplier: 2

  jpa:
    hibernate:
      ddl-auto: update
    show-sql: false
    properties:
      hibernate:
        format_sql: false
        highlight_sql: false
        use_sql_comments: false
        default_batch_fetch_size: 100
    open-in-view: false

custom:
  oauth:
    google:
      redirect-uri: https://www.app.lithub.site/login/oauth2/code/google
    naver:
      redirect-uri: https://www.app.lithub.site/login/oauth2/code/naver


  cookie:
    secure: true
    http-only: true
    same-site: None

  site:
    domain: lithub.site
    back-url: ${custom.prod.site.back-url}
    front-url: ${custom.prod.site.front-url}

  s3:
    bucket: ${custom.s3.bucket}
    base-profile-dir: ${custom.s3.base-profile-dir}

  redis:
    cache:
      host: ${custom.prod.redis.cache-host}
      port: ${custom.prod.redis.cache-port}
      password: ${custom.prod.redis.password}

management:
  endpoints:
    web:
      exposure:
        include: prometheus