# application-dev.yml

spring:
  datasource:
    url: ${custom.dev.db.url}
    username: ${custom.dev.db.username}
    password: ${custom.dev.db.password}
    driver-class-name: com.mysql.cj.jdbc.Driver

  docker:
    compose:
      enabled: false

  data:
    redis:
      host: ${custom.dev.redis.token-host}
      port: ${custom.dev.redis.token-port}

  rabbitmq:
    host: ${custom.dev.rabbitmq.host}
    port: ${custom.dev.rabbitmq.port}
    username: ${custom.dev.rabbitmq.username}
    password: ${custom.dev.rabbitmq.password}
    listener:
      simple:
        retry:
          enabled: true
          initial-interval: 1000
          max-attempts: 5
          max-interval: 10000
          multiplier: 2

  jpa:
    defer-datasource-initialization: true
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        format_sql: true
        highlight_sql: true
        use_sql_comments: true
        default_batch_fetch_size: 100
    open-in-view: false

  sql:
    init:
      mode: always
      encoding: utf-8
      schema-locations: classpath:index.sql

custom:
  cookie:
    secure: false
    http-only: false
    same-site: None

  site:
    domain: localhost
    back-url: ${custom.dev.site.back-url}
    front-url: ${custom.dev.site.front-url}

  file:
    upload-dir: ${custom.dev.site.file-upload-dir}

  redis:
    cache:
      host: ${custom.dev.redis.cache-host}
      port: ${custom.dev.redis.cache-port}