# application-dev.yml

spring:
  datasource:
    url: jdbc:mysql://localhost:3309/LitHub-dev
    username: root
    password: 1234
    driver-class-name: com.mysql.cj.jdbc.Driver

  data:
    redis:
      host: localhost
      port: 6380

  rabbitmq:
    host: localhost
    port: 5672
    username: guest
    password: guest
    listener:
      simple:
        retry:
          enabled: true
          initial-interval: 1000
          max-attempts: 5
          max-interval: 10000
          multiplier: 2

  jpa:
    defer-datasource-initialization: true
    hibernate:
      ddl-auto: create
    show-sql: true
    properties:
      hibernate:
        format_sql: true
        highlight_sql: true
        use_sql_comments: true
        default_batch_fetch_size: 100
    open-in-view: false

  sql:
    init:
      mode: always
      encoding: utf-8
      schema-locations: classpath:index.sql

custom:
  oauth:
    google:
      redirect-uri: http://localhost:8080/login/oauth2/code/google
    naver:
      redirect-uri: http://localhost:8080/login/oauth2/code/naver

  cookie:
    secure: false
    http-only: false
    same-site: None

  site:
    domain: localhost
    back-url: http://localhost:8080
    front-url: http://localhost:5173

  file:
    upload-dir: C:/Users/Sojinyoung/Desktop/LitHubStorage

  redis:
    cache:
      host: localhost
      port: 6382