# application-test.yml

spring:
  datasource:
    url: jdbc:mysql://${MYSQL_HOST_TEST}:${MYSQL_PORT_TEST}/${MYSQL_DATABASE_TEST}
    username: ${MYSQL_USERNAME_TEST}
    password: ${MYSQL_PASSWORD_TEST}
    driver-class-name: com.mysql.cj.jdbc.Driver

  jpa:
    hibernate:
      ddl-auto: create
    properties:
      hibernate:
        format_sql: true
        use_sql_comments: true

  docker:
    compose:
      enabled: false

  data:
    redis:
      host: ${REDIS_HOST_TEST}
      port: ${REDIS_PORT_TEST}

url:
  base: http://localhost:3000