# application-dev.yml

spring:
  datasource:
    url: jdbc:mysql://${MYSQL_HOST_DEV}:${MYSQL_PORT_DEV}/${MYSQL_DATABASE_DEV}
    username: ${MYSQL_USERNAME_DEV}
    password: ${MYSQL_PASSWORD_DEV}
    driver-class-name: com.mysql.cj.jdbc.Driver

  docker:
    compose:
      enabled: false

  data:
    redis:
      host: ${REDIS_HOST_DEV}
      port: ${REDIS_PORT_DEV}

url:
  base: http://localhost:3000