# application-dev.yml

spring:
  datasource:
    url: ${MYSQL_URL_DEV}
    username: ${MYSQL_USERNAME_DEV}
    password: ${MYSQL_PASSWORD_DEV}
    driver-class-name: com.mysql.cj.jdbc.Driver

  docker:
    compose:
      enabled: false

  data:
    redis:
      host: ${REDIS_HOST_DEV}
      port: ${REDIS_PORT_DEV}

  jpa:
    hibernate:
      ddl-auto: create
    show-sql: true
    properties:
      hibernate:
        format_sql: true
        highlight_sql: true
        use_sql_comments: true
        default_batch_fetch_size: 100
    open-in-view: false

management:
  endpoints:
    web:
      exposure:
        include: health, metrics, prometheus

custom:
  site:
    back-url: ${CUSTOM_SITE_BACK_URL_DEV}
    front-url: ${CUSTOM_SITE_FRONT_URL_DEV}

  file:
    upload-dir: ${CUSTOM_FILE_UPLOAD_DIR_DEV}

