# application-dev.yml

spring:
  datasource:
    url: ${MYSQL_URL_DEV}
    username: ${MYSQL_USERNAME_DEV}
    password: ${MYSQL_PASSWORD_DEV}
    driver-class-name: com.mysql.cj.jdbc.Driver

  docker:
    compose:
      enabled: false

  data:
    redis:
      host: ${REDIS_HOST_DEV}
      port: ${REDIS_PORT_DEV}

  rabbitmq:
    host: ${RABBITMQ_HOST_DEV}
    port: ${RABBITMQ_PORT_DEV}
    username: ${RABBITMQ_USERNAME_DEV}
    password: ${RABBITMQ_PASSWORD_DEV}
    listener:
      simple:
        retry:
          enabled: true
          initial-interval: 1000
          max-attempts: 5
          max-interval: 10000
          multiplier: 2

  jpa:
    defer-datasource-initialization: true
    hibernate:
      ddl-auto: create-drop
    show-sql: true
    properties:
      hibernate:
        format_sql: true
        highlight_sql: true
        use_sql_comments: true
        default_batch_fetch_size: 100
    open-in-view: false
  sql:
    init:
      mode: always
      encoding: utf-8
      schema-locations: classpath:index.sql

custom:
  site:
    domain: localhost
    back-url: ${CUSTOM_SITE_BACK_URL_DEV}
    front-url: ${CUSTOM_SITE_FRONT_URL_DEV}

  file:
    upload-dir: ${CUSTOM_FILE_UPLOAD_DIR_DEV}