# application.yml

spring:
  profiles:
    active: dev

  servlet:
    multipart:
      max-file-size: 5MB
      max-request-size: 20MB

  jwt:
    secret: ${JWT_SECRET}

  mail:
    host: ${MAIL_HOST}
    port: ${MAIL_PORT}
    username: ${MAIL_USERNAME}
    password: ${MAIL_PASSWORD}
    properties:
      mail.smtp.auth: true
      mail.smtp.ssl.enable: true
      mail.smtp.ssl.trust: ${MAIL_HOST}

  jpa:
    hibernate:
      ddl-auto: create
    show-sql: true
    properties:
      hibernate:
        format_sql: true
        highlight_sql: true
        use_sql_comments: true
        default_batch_fetch_size: 100
    open-in-view: false

server:
  port: 8080
  tomcat:
    max-swallow-size: 1GB
    max-http-form-post-size: 1GB

springdoc:
  api-docs:
    enabled: true
  default-produces-media-type: application/json;charset=UTF-8

custom:
  upload:
    max-image-size: 5MB
    max-file-size: 20MB
  dev:
    domain: localhost
    backUrl: "http://${custom.dev.domain}:${server.port}"
  site:
    backUrl: "${custom.dev.backUrl}"

file:
  upload-dir: C:/Users/Sojinyoung/Desktop/LitHubStorage

logging:
  level:
    org.hibernate.SQL: INFO
    org.hibernate.orm.jdbc.bind: OFF
    org.hibernate.orm.jdbc.extract: OFF
    org.springframework.transaction.interceptor: OFF