# application-test.yml

spring:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver

  autoconfigure:
    exclude: io.awspring.cloud.autoconfigure.s3.S3AutoConfiguration

  jpa:
    hibernate:
      ddl-auto: create

url:
  base: http://localhost:5173